language: java
jdk:
  - oraclejdk11
  - openjdk11
os:
  - linux
  - osx
  # The language 'java' is currently unsupported on the Windows Build Environment.
  #- windows

addons:
  sonarcloud:
    organization: "karstenroethig"

script:
  # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
  - mvn clean verify sonar:sonar -Pcoverage
